---
spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/dev
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

  servlet:
    context-path: "/bookslib"